In [7]:
import torch 
x=torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
X=torch.tensor([12,45])
Y=torch.tensor([3,90])
print(X>Y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([ True, False])


In [8]:
x=torch.arange(12)
X=x.reshape(3,4)
X
X=x.reshape(4,3)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# 运算符


In [11]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y
x+2

tensor([ 3.,  4.,  6., 10.])

In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [13]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
a*b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [16]:
a=torch.tensor([3.5,4.0])
a[0].item()

3.5

In [17]:
import os 
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [20]:
import pandas as pd 

data=pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [30]:
#data.iloc[:,0:2],data.iloc[:,0:3]
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs.mean())
inputs = inputs.fillna(inputs.mean())
print(inputs)

NumRooms    3.0
dtype: float64
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/tmp/ipykernel_10823/2232898474.py:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(inputs.mean())
/tmp/ipykernel_10823/2232898474.py:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs = inputs.fillna(inputs.mean())


In [50]:
#print(data)
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs['Alley'][2]="Sun"
print(inputs)
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)



   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   Sun
3       NaN   NaN
   NumRooms  Alley_Pave  Alley_Sun  Alley_nan
0       NaN           1          0          0
1       2.0           0          0          1
2       4.0           0          1          0
3       NaN           0          0          1


/tmp/ipykernel_10823/2130157088.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inputs['Alley'][2]="Sun"


In [60]:
X=torch.arange(48).reshape((4,3,4))
print(X)
X_Sum=X.sum(axis=0)
print(X_Sum,X_Sum.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]])
tensor([[ 72,  76,  80,  84],
        [ 88,  92,  96, 100],
        [104, 108, 112, 116]]) torch.Size([3, 4])


In [67]:
x = torch.arange(4, dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)
z=y.reshape((4,1))
print(z)
x*z

tensor([[1.],
        [1.],
        [1.],
        [1.]])


tensor([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]])

In [83]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B
x = torch.arange(4, dtype=torch.float32)
A,x,A*x,torch.mm(A,x.reshape(4,-1)),torch.mv(A,x)



(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([[ 0.,  1.,  4.,  9.],
         [ 0.,  5., 12., 21.],
         [ 0.,  9., 20., 33.],
         [ 0., 13., 28., 45.],
         [ 0., 17., 36., 57.]]),
 tensor([[ 14.],
         [ 38.],
         [ 62.],
         [ 86.],
         [110.]]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [84]:
r=torch.mm(A,x.reshape(4,-1))
r.shape,r.reshape(-1,5)[0]

(torch.Size([5, 1]), tensor([ 14.,  38.,  62.,  86., 110.]))

torch.mm 和 torch.mv的区别在于结果的维度或者shape，(1,5)还是单纯的5。 
tensor是一个向量，但是不是一个矩阵，这个是以前没有注意的地方。

In [101]:
import torch 
x = torch.arange(4.0,requires_grad=True)
y= 2* torch.dot(x,x) 
y

tensor(28., grad_fn=<MulBackward0>)

In [102]:
z=2*y
z.backward()
x.grad ,y.grad 


/home/liukun/anaconda3/envs/pytorch_env/lib/python3.8/site-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272068694/work/build/aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


(tensor([ 0.,  8., 16., 24.]), None)

In [108]:
#x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([6., 6., 6., 6.])